import type { DropdownSettings, WorkTypeDefinition } from "./types";

export const API_BASE_URL = "/api";

export const WORK_TYPE_DEFINITIONS: WorkTypeDefinition[] = [
  {
    code: "GEN-001",
    label: "Miscellaneous Work",
    category: "GENERAL",
    disposalDays: 7,
    priority: "LOW",
    isActive: true,
  },
  {
    code: "GEN-002",
    label: "Administrative Task",
    category: "GENERAL",
    disposalDays: 5,
    priority: "LOW",
    isActive: true,
  },
  {
    code: "GEN-003",
    label: "Meeting / Coordination",
    category: "GENERAL",
    disposalDays: 2,
    priority: "LOW",
    isActive: true,
  },

  {
    code: "DWG-001",
    label: "New Drawing Preparation",
    category: "DRAWING",
    disposalDays: 30,
    priority: "MEDIUM",
    isActive: true,
    requiresDocument: true,
  },
  {
    code: "DWG-002",
    label: "Drawing Amendment",
    category: "DRAWING",
    disposalDays: 15,
    priority: "MEDIUM",
    isActive: true,
    requiresDocument: true,
  },
  {
    code: "DWG-003",
    label: "Drawing Review",
    category: "DRAWING",
    disposalDays: 10,
    priority: "MEDIUM",
    isActive: true,
    requiresDocument: true,
  },
  {
    code: "DWG-004",
    label: "Drawing Approval",
    category: "DRAWING",
    disposalDays: 7,
    priority: "HIGH",
    isActive: true,
    requiresDocument: true,
  },
  {
    code: "DWG-005",
    label: "Drawing Re-issue",
    category: "DRAWING",
    disposalDays: 5,
    priority: "MEDIUM",
    isActive: true,
    requiresDocument: true,
  },

  {
    code: "SPEC-001",
    label: "Specification Preparation",
    category: "SPECIFICATION",
    disposalDays: 45,
    priority: "HIGH",
    isActive: true,
    requiresDocument: true,
  },
  {
    code: "SPEC-002",
    label: "Specification Review",
    category: "SPECIFICATION",
    disposalDays: 15,
    priority: "HIGH",
    isActive: true,
    requiresDocument: true,
  },
  {
    code: "SPEC-003",
    label: "Specification Amendment",
    category: "SPECIFICATION",
    disposalDays: 20,
    priority: "MEDIUM",
    isActive: true,
    requiresDocument: true,
  },
  {
    code: "SPEC-004",
    label: "Eligibility Criteria Preparation",
    category: "SPECIFICATION",
    disposalDays: 30,
    priority: "HIGH",
    isActive: true,
    requiresDocument: true,
  },

  {
    code: "TEND-001",
    label: "Tender Processing",
    category: "TENDER",
    disposalDays: 60,
    priority: "HIGH",
    isActive: true,
    consentApplicable: true,
  },
  {
    code: "TEND-002",
    label: "Tender Evaluation",
    category: "TENDER",
    disposalDays: 30,
    priority: "HIGH",
    isActive: true,
  },
  {
    code: "TEND-003",
    label: "Scope of Supply Review",
    category: "TENDER",
    disposalDays: 15,
    priority: "MEDIUM",
    isActive: true,
    requiresDocument: true,
  },
  {
    code: "TEND-004",
    label: "NIT Preparation",
    category: "TENDER",
    disposalDays: 21,
    priority: "HIGH",
    isActive: true,
  },

  {
    code: "SHOP-001",
    label: "Shop Inspection",
    category: "SHOP",
    disposalDays: 7,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "SHOP-002",
    label: "Works Inspection",
    category: "SHOP",
    disposalDays: 14,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "SHOP-003",
    label: "Trial Inspection",
    category: "SHOP",
    disposalDays: 5,
    priority: "HIGH",
    isActive: true,
  },
  {
    code: "SHOP-004",
    label: "Stage Inspection",
    category: "SHOP",
    disposalDays: 7,
    priority: "MEDIUM",
    isActive: true,
  },

  {
    code: "IC-001",
    label: "IC Preparation",
    category: "IC",
    disposalDays: 10,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "IC-002",
    label: "IC Review",
    category: "IC",
    disposalDays: 5,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "IC-003",
    label: "IC Approval",
    category: "IC",
    disposalDays: 3,
    priority: "HIGH",
    isActive: true,
  },

  {
    code: "AMND-001",
    label: "Amendment Processing",
    category: "AMENDMENT",
    disposalDays: 21,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "AMND-002",
    label: "Corrigendum Issue",
    category: "AMENDMENT",
    disposalDays: 10,
    priority: "MEDIUM",
    isActive: true,
  },

  {
    code: "VND-001",
    label: "Vendor Development",
    category: "VENDOR",
    disposalDays: 90,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "VND-002",
    label: "Vendor Evaluation",
    category: "VENDOR",
    disposalDays: 30,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "VND-003",
    label: "Vendor Inspection",
    category: "VENDOR",
    disposalDays: 14,
    priority: "MEDIUM",
    isActive: true,
  },

  {
    code: "EXT-001",
    label: "External Agency Work",
    category: "EXTERNAL",
    disposalDays: 30,
    priority: "LOW",
    isActive: true,
  },
  {
    code: "EXT-002",
    label: "RDSO Reference",
    category: "EXTERNAL",
    disposalDays: 21,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "EXT-003",
    label: "CLW Coordination",
    category: "EXTERNAL",
    disposalDays: 15,
    priority: "MEDIUM",
    isActive: true,
  },

  {
    code: "FAIL-001",
    label: "Failure Investigation",
    category: "FAILURE",
    disposalDays: 14,
    priority: "CRITICAL",
    isActive: true,
  },
  {
    code: "FAIL-002",
    label: "Root Cause Analysis",
    category: "FAILURE",
    disposalDays: 21,
    priority: "CRITICAL",
    isActive: true,
  },
  {
    code: "FAIL-003",
    label: "Corrective Action",
    category: "FAILURE",
    disposalDays: 30,
    priority: "HIGH",
    isActive: true,
  },

  {
    code: "INSP-001",
    label: "Type Test Inspection",
    category: "INSPECTION",
    disposalDays: 30,
    priority: "HIGH",
    isActive: true,
  },
  {
    code: "INSP-002",
    label: "Routine Inspection",
    category: "INSPECTION",
    disposalDays: 7,
    priority: "MEDIUM",
    isActive: true,
  },
  {
    code: "INSP-003",
    label: "Acceptance Inspection",
    category: "INSPECTION",
    disposalDays: 5,
    priority: "HIGH",
    isActive: true,
  },
  {
    code: "INSP-004",
    label: "Special Inspection",
    category: "INSPECTION",
    disposalDays: 14,
    priority: "HIGH",
    isActive: true,
  },
];

export const SECTION_TYPES: string[] = [
  "General",
  "Design",
  "Inspection",
  "Tender",
  "Workshop",
  "Quality",
  "Safety",
  "Electrical",
  "Mechanical",
  "Electronics",
];

export const CONCERNED_OFFICERS: string[] = [
  "SSE/Design",
  "JE/Design",
  "SSE/Inspection",
  "JE/Inspection",
  "SSE/Tender",
  "JE/Tender",
  "SSE/Workshop",
  "JE/Workshop",
  "CWE/Design",
  "DyCE/Design",
  "ADE/General",
];

export const AGENCIES: string[] = [
  "CLW",
  "RDSO",
  "CORE",
  "ICF",
  "RCF",
  "MCF",
  "COFMOW",
  "ABB",
  "Siemens",
  "BHEL",
  "Other",
];

export const DOCUMENT_CATEGORIES: string[] = [
  "DRAWING",
  "SPECIFICATION",
  "ELIGIBILITY_CRITERIA",
  "SCOPE_OF_SUPPLY",
  "SMI",
  "STANDARD",
  "TENDER",
  "SDR",
  "TEST_REPORT",
  "CERTIFICATE",
  "PROCEDURE",
  "OTHER",
];

export const DEFAULT_DROPDOWN_SETTINGS: DropdownSettings = {
  workTypes: WORK_TYPE_DEFINITIONS,
  sectionTypes: SECTION_TYPES,
  concernedOfficers: CONCERNED_OFFICERS,
  agencies: AGENCIES,
  documentCategories: DOCUMENT_CATEGORIES,
};

export const ROLE_LABELS: Record<string, string> = {
  admin: "System Admin",
  supervisor: "Supervisor",
  engineer: "Engineer",
  reviewer: "Reviewer",
  viewer: "Viewer",
};

export const INSPECTION_CATEGORIES = ["CAT-A", "CAT-B", "CAT-C", "CAT-D"] as const;

export const INSPECTION_CATEGORY_LABELS: Record<string, string> = {
  "CAT-A": "Category A — Safety Critical",
  "CAT-B": "Category B — Mission Critical",
  "CAT-C": "Category C — Important",
  "CAT-D": "Category D — Standard",
};

export const WORK_CATEGORY_LABELS: Record<string, string> = {
  GENERAL: "General",
  DRAWING: "Drawing",
  SPECIFICATION: "Specification",
  TENDER: "Tender",
  SHOP: "Shop",
  IC: "IC",
  AMENDMENT: "Amendment",
  VENDOR: "Vendor",
  EXTERNAL: "External",
  FAILURE: "Failure",
  INSPECTION: "Inspection",
};
