export const MOCK_DOCUMENTS = [
  {
    id: "DOC-2026-9021",
    name: "HVAC Sub-Assembly Wiring Diagram",
    type: "PDF",
    size: "4.2 MB",
    revision: "C.1",
    status: "Approved",
    author: "J. Halloway",
    owner: "Engineering Dept",
    date: "2026-03-20",
    linkedPL: "PL-55092",
    ocrStatus: "Completed",
    ocrConfidence: 98,
    category: "Electrical Schema",
    lifecycle: "Active",
    pages: 12,
    tags: ["Engineering", "Electrical", "Schematic"],
  },
  {
    id: "DOC-2026-9022",
    name: "Thermal Tolerance Specification v2",
    type: "DOCX",
    size: "1.8 MB",
    revision: "A.4",
    status: "In Review",
    author: "M. Chen",
    owner: "Compliance Team",
    date: "2026-03-21",
    linkedPL: "PL-55092",
    ocrStatus: "Processing",
    ocrConfidence: null,
    category: "Specification",
    lifecycle: "Draft",
    pages: 45,
    tags: ["Compliance", "Thermal"],
  },
  {
    id: "DOC-2026-9023",
    name: "Turbine Blade CAD Render (Section B)",
    type: "PNG",
    size: "12.5 MB",
    revision: "B.0",
    status: "Draft",
    author: "A. Kowalski",
    owner: "Design Ops",
    date: "2026-03-22",
    linkedPL: "PL-88104",
    ocrStatus: "Failed",
    ocrConfidence: 12,
    category: "CAD Output",
    lifecycle: "Draft",
    pages: 1,
    tags: ["Mechanical", "CAD", "WIP"],
  },
  {
    id: "DOC-2025-1104",
    name: "Legacy Actuator Calibrations",
    type: "PDF",
    size: "8.1 MB",
    revision: "F.2",
    status: "Obsolete",
    author: "S. Vance",
    owner: "Quality Assurance",
    date: "2025-11-14",
    linkedPL: "PL-11002",
    ocrStatus: "Completed",
    ocrConfidence: 85,
    category: "Calibration Log",
    lifecycle: "Archived",
    pages: 8,
    tags: ["Archive", "Calibration"],
  },
  {
    id: "DOC-2026-9040",
    name: "Q1 Material Yield Report",
    type: "XLSX",
    size: "3.4 MB",
    revision: "A.1",
    status: "Approved",
    author: "System_Auto",
    owner: "Operations",
    date: "2026-03-23",
    linkedPL: "N/A",
    ocrStatus: "Not Required",
    ocrConfidence: null,
    category: "Financial / Yield",
    lifecycle: "Active",
    pages: 3,
    tags: ["Report", "Materials"],
  },
  {
    id: "DOC-2026-1101",
    name: "Bogie Frame Stress Analysis Report",
    type: "PDF",
    size: "34.2 MB",
    revision: "C.0",
    status: "Approved",
    author: "D. Mukherjee",
    owner: "Bogie Design Division",
    date: "2025-06-10",
    linkedPL: "PL-38110000",
    ocrStatus: "Completed",
    ocrConfidence: 96,
    category: "Test Report",
    lifecycle: "Active",
    pages: 48,
    tags: ["Structural", "FEA", "Safety Vital"],
  },
  {
    id: "DOC-2026-1201",
    name: "Brake System Type Test Report",
    type: "PDF",
    size: "42.1 MB",
    revision: "B.2",
    status: "Approved",
    author: "S. Patel",
    owner: "Brake Systems Division",
    date: "2025-04-18",
    linkedPL: "PL-38111000",
    ocrStatus: "Completed",
    ocrConfidence: 94,
    category: "Test Report",
    lifecycle: "Active",
    pages: 86,
    tags: ["Safety Vital", "Brake", "Type Test"],
  },
  {
    id: "DOC-2026-2001",
    name: "Traction Motor Type Test Report",
    type: "PDF",
    size: "28.4 MB",
    revision: "B.0",
    status: "Approved",
    author: "A. Sharma",
    owner: "Electrical Design Division",
    date: "2025-04-10",
    linkedPL: "PL-38120000",
    ocrStatus: "Completed",
    ocrConfidence: 97,
    category: "Test Report",
    lifecycle: "Active",
    pages: 124,
    tags: ["Electrical", "Traction Motor"],
  },
  {
    id: "DOC-2026-3001",
    name: "Transformer Routine Test Certificate",
    type: "PDF",
    size: "15.6 MB",
    revision: "C.0",
    status: "Approved",
    author: "P. Gupta",
    owner: "Transformer Division",
    date: "2025-10-28",
    linkedPL: "PL-38130000",
    ocrStatus: "Completed",
    ocrConfidence: 99,
    category: "Certificate",
    lifecycle: "Active",
    pages: 22,
    tags: ["Electrical", "Transformer"],
  },
  {
    id: "DOC-2026-5001",
    name: "Pantograph Type Test Report",
    type: "PDF",
    size: "18.2 MB",
    revision: "A.5",
    status: "Approved",
    author: "M. Reddy",
    owner: "Current Collection Division",
    date: "2025-05-20",
    linkedPL: "PL-38150000",
    ocrStatus: "Completed",
    ocrConfidence: 91,
    category: "Test Report",
    lifecycle: "Active",
    pages: 56,
    tags: ["High Voltage", "Pantograph"],
  },
  {
    id: "DOC-2026-4001",
    name: "Control System Architecture Specification",
    type: "PDF",
    size: "22.1 MB",
    revision: "B.3",
    status: "Approved",
    author: "K. Joshi",
    owner: "Electronics Division",
    date: "2025-12-05",
    linkedPL: "PL-38140000",
    ocrStatus: "Completed",
    ocrConfidence: 93,
    category: "Specification",
    lifecycle: "Active",
    pages: 78,
    tags: ["Electronics", "TCMS", "Safety Vital"],
  },
  {
    id: "DOC-2026-9301",
    name: "Brake Cylinder Seal Arrangement",
    type: "PDF",
    size: "18.6 MB",
    revision: "D.2",
    status: "Approved",
    author: "A. Rao",
    owner: "Design Office",
    date: "2026-02-18",
    linkedPL: "PL-38111000",
    ocrStatus: "Completed",
    ocrConfidence: 98,
    category: "Electrical Schema",
    lifecycle: "Active",
    pages: 14,
    tags: ["Drawing", "Brake Cylinder", "Released"],
  },
  {
    id: "DOC-2026-9302",
    name: "Brake Cylinder Seal Arrangement",
    type: "PDF",
    size: "18.6 MB",
    revision: "D.2",
    status: "In Review",
    author: "P. Sen",
    owner: "Quality Cell",
    date: "2026-02-14",
    linkedPL: "PL-38111000",
    ocrStatus: "Completed",
    ocrConfidence: 96,
    category: "Electrical Schema",
    lifecycle: "Duplicate Candidate",
    pages: 14,
    tags: ["Drawing", "Scanner Import"],
  },
  {
    id: "DOC-2026-9303",
    name: "Brake Cylinder Seal Arrangement",
    type: "PDF",
    size: "18.6 MB",
    revision: "D.2",
    status: "Obsolete",
    author: "M. Khanna",
    owner: "Vendor Development",
    date: "2026-01-27",
    linkedPL: "PL-38111000",
    ocrStatus: "Completed",
    ocrConfidence: 95,
    category: "Electrical Schema",
    lifecycle: "Archived",
    pages: 14,
    tags: ["Drawing", "Vendor Copy"],
  },
  {
    id: "DOC-2026-9311",
    name: "Vendor Qualification Pack – Axle Bearing Supplier",
    type: "PDF",
    size: "6.0 MB",
    revision: "A.1",
    status: "Approved",
    author: "M. Khanna",
    owner: "Vendor Development",
    date: "2026-03-03",
    linkedPL: "PL-38130000",
    ocrStatus: "Completed",
    ocrConfidence: 91,
    category: "Certificate",
    lifecycle: "Active",
    pages: 32,
    tags: ["Vendor", "Qualification"],
  },
  {
    id: "DOC-2026-9312",
    name: "Vendor Qualification Pack – Axle Bearing Supplier",
    type: "PDF",
    size: "6.0 MB",
    revision: "A.1",
    status: "Draft",
    author: "P. Sen",
    owner: "Quality Cell",
    date: "2026-02-26",
    linkedPL: "PL-38130000",
    ocrStatus: "Processing",
    ocrConfidence: null,
    category: "Certificate",
    lifecycle: "Draft",
    pages: 31,
    tags: ["Vendor", "Imported"],
  },
  {
    id: "DOC-2026-9313",
    name: "Vendor Qualification Pack – Axle Bearing Supplier",
    type: "PDF",
    size: "6.0 MB",
    revision: "A.1",
    status: "Obsolete",
    author: "A. Rao",
    owner: "Vendor Development",
    date: "2025-11-05",
    linkedPL: "PL-38130000",
    ocrStatus: "Not Required",
    ocrConfidence: null,
    category: "Certificate",
    lifecycle: "Archived",
    pages: 32,
    tags: ["Vendor", "Archive"],
  },
  {
    id: "DOC-2026-9321",
    name: "HV Control Cabinet Interface Specification",
    type: "PDF",
    size: "9.1 MB",
    revision: "B.3",
    status: "Approved",
    author: "A. Rao",
    owner: "Design Office",
    date: "2026-02-01",
    linkedPL: "PL-38140000",
    ocrStatus: "Completed",
    ocrConfidence: 93,
    category: "Specification",
    lifecycle: "Active",
    pages: 44,
    tags: ["Interface", "HV Control"],
  },
  {
    id: "DOC-2026-9322",
    name: "HV Control Cabinet Interface Specification",
    type: "PDF",
    size: "9.1 MB",
    revision: "B.4",
    status: "Approved",
    author: "P. Sen",
    owner: "Design Office",
    date: "2026-03-19",
    linkedPL: "PL-38140000",
    ocrStatus: "Completed",
    ocrConfidence: 94,
    category: "Specification",
    lifecycle: "Active",
    pages: 45,
    tags: ["Interface", "HV Control", "Latest"],
  },
  {
    id: "DOC-2026-9331",
    name: "Door Controller Commissioning Procedure",
    type: "PDF",
    size: "6.6 MB",
    revision: "C.0",
    status: "Approved",
    author: "A. Rao",
    owner: "Design Office",
    date: "2026-03-08",
    linkedPL: "PL-38150000",
    ocrStatus: "Completed",
    ocrConfidence: 97,
    category: "Procedure",
    lifecycle: "Active",
    pages: 27,
    tags: ["Procedure", "Door Controller"],
  },
  {
    id: "DOC-2026-9332",
    name: "Door Controller Commissioning Procedure",
    type: "PDF",
    size: "6.6 MB",
    revision: "C.0",
    status: "In Review",
    author: "M. Khanna",
    owner: "Quality Cell",
    date: "2026-02-23",
    linkedPL: "PL-38150000",
    ocrStatus: "Completed",
    ocrConfidence: 95,
    category: "Procedure",
    lifecycle: "Duplicate Candidate",
    pages: 27,
    tags: ["Procedure", "Scanner Import"],
  },
  {
    id: "DOC-2025-9333",
    name: "Door Controller Commissioning Procedure",
    type: "PDF",
    size: "6.6 MB",
    revision: "C.0",
    status: "Obsolete",
    author: "P. Sen",
    owner: "Quality Cell",
    date: "2025-09-11",
    linkedPL: "PL-38150000",
    ocrStatus: "Completed",
    ocrConfidence: 92,
    category: "Procedure",
    lifecycle: "Archived",
    pages: 27,
    tags: ["Procedure", "Archive"],
  },
];

export const MOCK_PL_RECORDS = [
  {
    id: "PL-55092",
    title: "Turbine Housing Thermal Control Node",
    status: "Active",
    lifecycle: "Production",
    owner: "M. Chen",
    lastUpdated: "2026-03-21",
    description:
      "Core PL record managing the thermal and electrical specifications for the main turbine housing unit.",
    linkedDocs: ["DOC-2026-9021", "DOC-2026-9022"],
    linkedBOMs: ["SUB-1100", "PART-1102"],
    cases: ["CAS-992"],
    ledgerEntries: 14,
  },
  {
    id: "PL-88104",
    title: "Advanced Propulsion Sub-System",
    status: "In Development",
    lifecycle: "Prototyping",
    owner: "A. Kowalski",
    lastUpdated: "2026-03-22",
    description: "Next-gen propulsion mechanics including new aerodynamic CAD outputs.",
    linkedDocs: ["DOC-2026-9023"],
    linkedBOMs: ["ASSY-1000"],
    cases: [],
    ledgerEntries: 5,
  },
  {
    id: "PL-11002",
    title: "Legacy Actuator MK-I",
    status: "Obsolete",
    lifecycle: "End of Life",
    owner: "S. Vance",
    lastUpdated: "2025-11-14",
    description: "Depreciated actuator calibration and specification records.",
    linkedDocs: ["DOC-2025-1104"],
    linkedBOMs: ["PART-9901 (Legacy)"],
    cases: ["CAS-104", "CAS-209"],
    ledgerEntries: 89,
  },
];

export const MOCK_AUDIT_LOG = [
  {
    id: "EVT-001",
    action: "Document Uploaded",
    entity: "DOC-2026-9040",
    user: "System_Auto",
    timestamp: "2026-03-23 08:00",
    module: "Documents",
  },
  {
    id: "EVT-002",
    action: "OCR Completed",
    entity: "DOC-2026-9021",
    user: "OCR Engine",
    timestamp: "2026-03-22 16:45",
    module: "OCR",
  },
  {
    id: "EVT-003",
    action: "Approval Submitted",
    entity: "DOC-2026-9022",
    user: "M. Chen",
    timestamp: "2026-03-21 11:20",
    module: "Approvals",
  },
  {
    id: "EVT-004",
    action: "Case Created",
    entity: "CAS-992",
    user: "J. Halloway",
    timestamp: "2026-03-15 09:00",
    module: "Cases",
  },
  {
    id: "EVT-005",
    action: "Login",
    entity: "USR-001",
    user: "a.kowalski",
    timestamp: "2026-03-24 08:30",
    module: "Auth",
  },
];
